### PR TITLE
Add new parameter to allow ID generation by function call

### PR DESCRIPTION
**Pull request by MaikMichel**
this is userful when you are not using sequences and need a generated UID for example. with that parameter in place you are able to use something like that:

...
p_id_function_call     => 'to_number(sys_guid(), ''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'')'
...

### CODE REVIEW

**Comment by ogobrecht** [comment]
Hi Maik,

I am wondering why you need a new parameter for this. You could use the existing parameter [p_enable_column_defaults](https://github.com/OraMUC/table-api-generator/blob/master/docs/parameters.md#p_enable_column_defaults-since-v050) and  the generator would pick up the column defaults from the dictionary for the create methods. That implies that you have set the column default on your table. But for me this is the only way to do it. Otherwise only the table API is knowing your logic, not the table itself.

Let me know what you think.

Best regards,
Ottmar

**Comment by MaikMichel** [comment]
Hi Ottmar,

this is a slightly different use case. The new parameter has a similar task as the parameter with the SequenceName. Basically I wanted to rename this one, so you could have just used "sequencename.nextval". But for backward compatibility reasons I decided against it.

In our current projects, we actually have the same triggers everywhere. These fill the auditcolumns and the PK column if it is null. Since you / the TableAPI now support that the auditcolumns are filled directly by the API, it is only logical for us to have the PK column filled by the API as well. And if this is explicitly defined, it is easier to understand for others.

Does this make sense?

**Comment by ogobrecht** [comment]
Hi Maik,

this is working today - you can complete remove your triggers, but you need to define proper default values on your tables. At the end your table should handle the default value when possible.

Here an example:

```sql
create table t (
    id number default on null to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') primary key,
    text varchar2(100) not null);

begin
    om_tapigen.compile_api (
        p_table_name             => 'T',
        p_enable_column_defaults => true );
end;
/
```

Generated create_row methods:

```sql
  FUNCTION create_row (
    p_id   IN "T"."ID"%TYPE   DEFAULT to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')  /*PK*/,
    p_text IN "T"."TEXT"%TYPE  )
  RETURN "T"."ID"%TYPE;

  PROCEDURE create_row (
    p_id   IN "T"."ID"%TYPE   DEFAULT to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')  /*PK*/,
    p_text IN "T"."TEXT"%TYPE  );
```

Usage examples:

```sql
begin
    -- usage with positional parameters (not recommended)
    insert into t values( null, 'row 1' ); -- table knows how to work with given null values
    t_api.create_row(     null, 'row 2' ); -- api does not care about given null values, the table will handle this correctly

    -- usage with named parameters
    insert into t (id, text) values( null,           'row 3' );
    t_api.create_row(        p_id => null, p_text => 'row 4' );

    -- usage with named parameters, defaults omitted - this should be your standard usage for such tables
    insert into t (text) values( 'row 5' );
    t_api.create_row(p_text  =>  'row 6' );

    commit;
end;
/
```

**Comment by MaikMichel** [comment]
Hi Ottmar,

I actually want to keep Logic out of the table definition here. So I can fill the column today with one method and tomorrow with another. We have that in today's projects as well and it allows us an additional barrier here, for inserts that don't come through the API. Even though this might be possible with other methods as well.

**Comment by ogobrecht** [comment]
Hi Maik,

let me say it in this way: If we had to implement the table api generator again today, it would have fewer parameters and the use of the column defaults would be standard (without extra parameters for it). There would also be no parameter for the sequence - this can be used as column default like any other expression.

Don't get us wrong - we are happy to see engagement and ideas. I had a discussion with André and we both don't see the need for another parameter. If you want today this expression and tomorrow another one for your ID columns you can do it with the existing generator - simply alter your table and regenerate the table API.

For the future: we have a development branch and we don't accept pull requests direct to master. So, please open pull requests against our development branch. We have then the chance to do our testing and maybe correct things before we merge into master.

Hopefully you can understand our position regarding the new parameter. Again - don't get us wrong...

Best regards
Ottmar

**Pull request closed without merging**
